# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupLabelling.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(889, 456)
        # Create a scroll area widget to hold the radio buttons
        scroll_area = QtWidgets.QScrollArea(Dialog)
        scroll_area.setGeometry(QtCore.QRect(120, 330, 631, 50))
        scroll_area.setWidgetResizable(True)

        scroll_widget = QtWidgets.QWidget()
        scroll_area.setWidget(scroll_widget)
        scroll_layout = QtWidgets.QVBoxLayout(scroll_widget)

        # Create True and False radio buttons and add them to the layout
        true_radio_button = QtWidgets.QRadioButton("True")
        false_radio_button = QtWidgets.QRadioButton("False")
        scroll_layout.addWidget(true_radio_button)
        scroll_layout.addWidget(false_radio_button)

        self.tbl_MatchingRecords = QtWidgets.QTableWidget(Dialog)
        self.tbl_MatchingRecords.setGeometry(QtCore.QRect(120, 140, 631, 181))
        self.tbl_MatchingRecords.setObjectName("tbl_MatchingRecords")
        self.tbl_MatchingRecords.setColumnCount(3)
        self.tbl_MatchingRecords.setHorizontalHeaderLabels(["Key", "Value", "Output"])  # Add the "Output" column
        self.tbl_MatchingRecords.horizontalHeader().setStretchLastSection(True)

        # Your existing table widget
        # self.tbl_CurrentExample = QtWidgets.QTableWidget(Dialog)
        # self.tbl_CurrentExample.setGeometry(QtCore.QRect(120, 140, 631, 181))
        # self.tbl_CurrentExample.setObjectName("tbl_CurrentExample")
        # self.tbl_CurrentExample.setColumnCount(2)
        # self.tbl_CurrentExample.setRowCount(0)
        # item = QtWidgets.QTableWidgetItem()
        # self.tbl_CurrentExample.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tbl_CurrentExample.setHorizontalHeaderItem(1, item)
        # self.tbl_CurrentExample.horizontalHeader().setStretchLastSection(True)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(260, 80, 81, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(460, 80, 81, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(180, 80, 81, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(380, 80, 81, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(570, 80, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        # item = self.tbl_CurrentExample.horizontalHeaderItem(0)
        # item.setText(_translate("Dialog", "Key"))
        # item = self.tbl_CurrentExample.horizontalHeaderItem(1)
        # item.setText(_translate("Dialog", "Value"))
        self.comboBox.setItemText(0, _translate("Dialog", "Status"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Option 2"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Key :"))
        self.plainTextEdit_2.setPlainText(_translate("Dialog", "Value :\n"""))
        self.pushButton.setText(_translate("Dialog", "LABEL"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
