# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        #self.setWindowFlag(QtCore.Qt.WindowMaximizeButtonHint, True)
        MainWindow.resize(960, 720)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../res/ML4CYBER_Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # The horizontal layout for the widget to help resizing the window
        self.hlayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.hlayout.setObjectName("hlayout")
        self.hlayout.setContentsMargins(0, 0, 0, 0)
        self.hlayout.setSpacing(0)
        # The vertical layout of the widget to help resizing the window
        self.vlayout = QtWidgets.QVBoxLayout()
        self.vlayout.setObjectName("vlayout")
        self.vlayout.setContentsMargins(50, 0, 50, 50)
        self.vlayout.setSpacing(60)

        # Adding the buttons to the vertical layout
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 30, 100))
        self.label.setObjectName("label")
        self.vlayout.addWidget(self.label)
        self.btn_Datasets = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Datasets.setObjectName("btn_Datasets")
        self.btn_Datasets.setGeometry(QtCore.QRect(120, 200, 30, 100))
        self.vlayout.addWidget(self.btn_Datasets)
        self.btn_Models = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Models.setObjectName("btn_Models")
        self.btn_Models.setGeometry(QtCore.QRect(120, 320, 30, 100))
        self.vlayout.addWidget(self.btn_Models)
        # 09/14/2023 (adding risk button)
        self.btn_Risk = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Risk.setObjectName("btn_Risk")
        self.btn_Risk.setGeometry(QtCore.QRect(120, 320, 30, 100))
        self.vlayout.addWidget(self.btn_Risk)

        self.btn_Predictions = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Predictions.setObjectName("btn_Predictions")
        self.btn_Predictions.setGeometry(QtCore.QRect(120, 440, 30, 100))
        self.vlayout.addWidget(self.btn_Predictions)
        self.btn_Help = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Help.setObjectName("btn_Help")
        self.btn_Help.setGeometry(QtCore.QRect(120, 560, 30, 100))
        self.vlayout.addWidget(self.btn_Help)
        
        # Adding the vertical layout to the horizontal layout
        self.hlayout.addLayout(self.vlayout)
        
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_Datasets.setFont(font)
        self.btn_Datasets.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:30px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 75 20pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:16px 31px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Datasets.setObjectName("btn_Datasets")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_Models.setFont(font)
        self.btn_Models.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:30px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 75 20pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:16px 31px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Models.setObjectName("btn_Models")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_Predictions.setFont(font)
        self.btn_Predictions.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:30px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 75 20pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:16px 31px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        # 09/14/2023
        self.btn_Risk.setObjectName("btn_Risk")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_Risk.setFont(font)
        self.btn_Risk.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:30px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 75 20pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:16px 31px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Predictions.setObjectName("btn_Predictions")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.btn_Help.setFont(font)
        self.btn_Help.setStyleSheet(
            "* {\n"
            "    background-color:#ffffff;\n"
            "    border-radius:30px;\n"
            "    border:6px solid #5d64b0;\n"
            "    color:#355398;\n"
            '    font: 75 20pt "Times";\n'
            "    font-weight: bold;\n"
            "    padding:16px 31px;\n"
            "    text-decoration:none;\n"
            "}\n"
            "*:hover {\n"
            "    background-color:#def2ff;\n"
            "}\n"
            "*:active {\n"
            "    position:relative;\n"
            "    top:1px;\n"
            "}"
        )
        self.btn_Help.setObjectName("btn_Help")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/menu/vinci.png"))
        self.label.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vinci ML Tool"))
        self.btn_Datasets.setText(_translate("MainWindow", "DATASETS"))
        self.btn_Models.setText(_translate("MainWindow", "MODEL TRAINING"))
        # 09/14/2023
        self.btn_Risk.setText(_translate("MainWindow", "RISK"))
        self.btn_Predictions.setText(_translate("MainWindow", "PREDICTIONS"))
        self.btn_Help.setText(_translate("MainWindow", "HELP"))


import menu_res_rc
