# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'risk_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RiskInfoWindow(object):
    def setupUi(self, RiskInfoWindow):
        RiskInfoWindow.setObjectName("RiskInfoWindow")
        RiskInfoWindow.resize(960, 480)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        RiskInfoWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        RiskInfoWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../res/ML4CYBER_Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On
        )
        RiskInfoWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(RiskInfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 831, 227))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/menu/risk_score.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 390, 831, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 831, 121))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        RiskInfoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RiskInfoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        RiskInfoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RiskInfoWindow)
        self.statusbar.setObjectName("statusbar")
        RiskInfoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RiskInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(RiskInfoWindow)

    def retranslateUi(self, RiskInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        RiskInfoWindow.setWindowTitle(
            _translate("RiskInfoWindow", "CWSS Information | Vinci ML Tool")
        )
        self.label_4.setText(
            _translate("RiskInfoWindow", "Note: Scoring not provided by CWE")
        )
        self.label.setText(
            _translate(
                "RiskInfoWindow",
                '<html><head/><body><p><span style=" font-size:18pt;">The Common Weakness Scoring System (CWSS) provides a mechanism for prioritizing software weaknesses in a consistent, flexible, open manner. </span></p></body></html>',
            )
        )


import menu_res_rc
